# Generated by scripts/gen-formula.sh for v0.1.0 -- do not edit manually.
class Jbase64 < Formula
  desc "Base64 encode/decode helper tool"
  homepage "https://github.com/mhus/mhus-jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/mhus-jknife/releases/download/v0.1.0/jbase64-0.1.0-macos-x86_64.tar.gz"
      sha256 "c9b30389422e451d84641b39a188aa1942faff07e3cce1c906d345e544d78f29"
    else
      url "https://github.com/mhus/mhus-jknife/releases/download/v0.1.0/jbase64-0.1.0-macos-aarch64.tar.gz"
      sha256 "69dd774d24191f6d9f9b455a3ae29733f6e782136befee7b1fed764271bf7219"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/mhus-jknife/releases/download/v0.1.0/jbase64-0.1.0-linux-x86_64.tar.gz"
      sha256 "82d5a4378bbb79504bd4adc5bdcaa0829537b4e1f9e01cae71c1d21247fb445b"
    else
      url "https://github.com/mhus/mhus-jknife/releases/download/v0.1.0/jbase64-0.1.0-linux-aarch64.tar.gz"
      sha256 "ea5e41e27383986abece5011d6ea5242fac8a10971230fea16de9c049c7bfdb8"
    end
  end

  def install
    bin.install "jbase64"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jbase64 --version")
  end
end
