# Generated by scripts/gen-formula.sh for v0.3.0 -- do not edit manually.
class Jbase64 < Formula
  desc "Base64 encode/decode helper tool"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jbase64-0.3.0-macos-x86_64.tar.gz"
      sha256 "5ae503162f1921b345af5fc09ab1dc09d8c19c0946d88ef814b9ffb03d1233f3"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jbase64-0.3.0-macos-aarch64.tar.gz"
      sha256 "46660674e89cde409d1fb31a9441e103077140d14151cea6370cbe566dafcbe8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jbase64-0.3.0-linux-x86_64.tar.gz"
      sha256 "b9c729b86ddcc98b4b1fef29972ff576dae821c421150947ccfbe12a9ef21307"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jbase64-0.3.0-linux-aarch64.tar.gz"
      sha256 "4c65905a3a2180421146529d6aa20f3345ba427d9aab5d24c09d7188665e1beb"
    end
  end

  def install
    bin.install "jbase64"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jbase64 --version")
  end
end
