# Generated by scripts/gen-formula.sh for v0.2.0 -- do not edit manually.
class Jbase64 < Formula
  desc "Base64 encode/decode helper tool"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jbase64-0.2.0-macos-x86_64.tar.gz"
      sha256 "9bd6a7bf7e1d3e77e19dd4186cf43f7721be6236aeee8a68b1126e95f1bb9b92"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jbase64-0.2.0-macos-aarch64.tar.gz"
      sha256 "6e15d8aa606107277d59c617da17502d96472f2493abd588d514905273694058"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jbase64-0.2.0-linux-x86_64.tar.gz"
      sha256 "be864a99fd7b3d74434bd76dc2edc303dd4362c675da80caaf40295b1d085dc6"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jbase64-0.2.0-linux-aarch64.tar.gz"
      sha256 "629302b08bc07a16e3ad27384575cdf23ba266cfb79cc7559633837f76fd3998"
    end
  end

  def install
    bin.install "jbase64"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jbase64 --version")
  end
end
