# Generated by scripts/gen-formula.sh for v0.3.0 -- do not edit manually.
class Jjson < Formula
  desc "JSON helper tool (validate, pretty, compact, get)"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jjson-0.3.0-macos-x86_64.tar.gz"
      sha256 "d5ec0a8eb047fff780d082931b8d3f121d83a5388504abf2cc78a335df062024"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jjson-0.3.0-macos-aarch64.tar.gz"
      sha256 "af55b9cb7fe970aedd886b48a07c394829bb108cad6a3e5d4e12dc71fba9b79c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jjson-0.3.0-linux-x86_64.tar.gz"
      sha256 "61f38c1074ade8b7e5232ff062ef22f62d790b7659d7f92485e5f2029dc203a9"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jjson-0.3.0-linux-aarch64.tar.gz"
      sha256 "91abe6f1a1fe95852c6857ac86912661b12664bcd3b6cbef835720cf78f04b4b"
    end
  end

  def install
    bin.install "jjson"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jjson --version")
  end
end
