# Generated by scripts/gen-formula.sh for v0.3.0 -- do not edit manually.
class Jllm < Formula
  desc "LLM tool family based on langchain4j (ask, stream, request, models)"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jllm-0.3.0-macos-x86_64.tar.gz"
      sha256 "0a889ada525ba0e1f1a826000335c0dac848e49f4b5682905bc3640a1aacb2e9"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jllm-0.3.0-macos-aarch64.tar.gz"
      sha256 "40a30c25077b3089fa7eed806755d05d7c9352b457506efb9bac6954d41a9bad"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jllm-0.3.0-linux-x86_64.tar.gz"
      sha256 "a7f77fced1e5fb9955cb8a41e2c67d4ee67e2fd80364b3fb1dd5ee32044c8240"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jllm-0.3.0-linux-aarch64.tar.gz"
      sha256 "35e0520c26dce0978f1014c6917bbc6da4cb3a9e2721620d2474eac84a370fc3"
    end
  end

  def install
    bin.install "jllm"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jllm --version")
  end
end
