# Generated by scripts/gen-formula.sh for v0.3.0 -- do not edit manually.
class Jperiod < Formula
  desc "Period/duration converter and parser helper tool"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jperiod-0.3.0-macos-x86_64.tar.gz"
      sha256 "b256a8a8e0ed4bf799c48cdb103bf6896651fbf8eda1e83a3318b4f6f6b275af"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jperiod-0.3.0-macos-aarch64.tar.gz"
      sha256 "add629c652023e80ec0cf758f9139b499d2f458c09da048f557921eebad9056a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jperiod-0.3.0-linux-x86_64.tar.gz"
      sha256 "a83a298d12ae4b2eeebc0aae1d322580663568d805117d05bab5048393c095c9"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jperiod-0.3.0-linux-aarch64.tar.gz"
      sha256 "290f6fc4a1603d414ce35e857f7ae651c8839010ff9627af7724fc7bd7027ac6"
    end
  end

  def install
    bin.install "jperiod"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jperiod --version")
  end
end
