# Generated by scripts/gen-formula.sh for v0.2.0 -- do not edit manually.
class Jperiod < Formula
  desc "Period/duration converter and parser helper tool"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jperiod-0.2.0-macos-x86_64.tar.gz"
      sha256 "9651608b31fee9b5c5eb8ae88cdda1454d380b9f4641dc3cb96583e6ae30c009"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jperiod-0.2.0-macos-aarch64.tar.gz"
      sha256 "50b4959c8799b723d711cc93de050573a9ec833275ce5e9378b7a12302bf8f5d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jperiod-0.2.0-linux-x86_64.tar.gz"
      sha256 "c1fd852ea75f1419049e20346b35d24d3fc6dbb6c76c44517c16594464e12ae1"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jperiod-0.2.0-linux-aarch64.tar.gz"
      sha256 "29f2c1f69040f226431f32bcbaa6ee7d38bf70969d1ec4118da7171ecf8e0456"
    end
  end

  def install
    bin.install "jperiod"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jperiod --version")
  end
end
