# Generated by scripts/gen-formula.sh for v0.3.0 -- do not edit manually.
class Jregex < Formula
  desc "Java regex helper tool (match, find, replace)"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jregex-0.3.0-macos-x86_64.tar.gz"
      sha256 "258205baca79993d045adef465a26304f000b8656cfe098da79100dba5e1c8e8"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jregex-0.3.0-macos-aarch64.tar.gz"
      sha256 "0a622ad1668adcb2f34c4ff596ad9291949ff3c7400716ae52fa8fe5443bdc1f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jregex-0.3.0-linux-x86_64.tar.gz"
      sha256 "9e1fdfc7d590f35395748691f39b6f7ae14f282ffdb6ca28135307c788b31a04"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jregex-0.3.0-linux-aarch64.tar.gz"
      sha256 "a84815ef9069a2f9c36a7051d89358dabb94bd9d561df9e4dea80f6d316efebb"
    end
  end

  def install
    bin.install "jregex"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jregex --version")
  end
end
