# Generated by scripts/gen-formula.sh for v0.2.0 -- do not edit manually.
class Jregex < Formula
  desc "Java regex helper tool (match, find, replace)"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jregex-0.2.0-macos-x86_64.tar.gz"
      sha256 "da2978e255549c6adf49eb3db50c5659572136cd5a413560d20252d4d8360f76"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jregex-0.2.0-macos-aarch64.tar.gz"
      sha256 "d7155f0ea3857f57bf3dd1db2cb058a148a0d6077c6fe84b8683a860a2158601"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jregex-0.2.0-linux-x86_64.tar.gz"
      sha256 "76cec6d8a8dd7667467b41473abd304cc71710c3c7b6a6a1271913d1ea46a5b5"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jregex-0.2.0-linux-aarch64.tar.gz"
      sha256 "a8e23b34b0810b121d5140dfeb00f1a2c8a2b5c438f0d9de0fe4a48cb8808d0b"
    end
  end

  def install
    bin.install "jregex"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jregex --version")
  end
end
