# Generated by scripts/gen-formula.sh for v0.1.0 -- do not edit manually.
class Jregex < Formula
  desc "Java regex helper tool (match, find, replace)"
  homepage "https://github.com/mhus/mhus-jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/mhus-jknife/releases/download/v0.1.0/jregex-0.1.0-macos-x86_64.tar.gz"
      sha256 "80979b178c6e8ad81436455b48445ce2868cb406329193c75316fcbd62eb5525"
    else
      url "https://github.com/mhus/mhus-jknife/releases/download/v0.1.0/jregex-0.1.0-macos-aarch64.tar.gz"
      sha256 "e4c7954388b9e6e119d183a08d255385149cab3b7dbd13c4f059fbcab972bd3d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/mhus-jknife/releases/download/v0.1.0/jregex-0.1.0-linux-x86_64.tar.gz"
      sha256 "be14aaa4cb9ad5eba39cda9e78320a6aa2c60f01be59bb6bbd0597a57e8e9575"
    else
      url "https://github.com/mhus/mhus-jknife/releases/download/v0.1.0/jregex-0.1.0-linux-aarch64.tar.gz"
      sha256 "cbf045235f32c1b61d4531d84f3acce7486ca5077690646311549bdb10badabd"
    end
  end

  def install
    bin.install "jregex"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jregex --version")
  end
end
