# Generated by scripts/gen-formula.sh for v0.3.0 -- do not edit manually.
class Jsec < Formula
  desc "Security tool family based on the java security framework (hash, keys, encrypt, sign)"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jsec-0.3.0-macos-x86_64.tar.gz"
      sha256 "ddbd4610171ecfbb82062b623ba812888715d3efeed9e049481e104974e908b9"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jsec-0.3.0-macos-aarch64.tar.gz"
      sha256 "51dbe77e41d42fd665376a8bd8da447e15d32d37986e84ad92f65a903d975dcf"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jsec-0.3.0-linux-x86_64.tar.gz"
      sha256 "3dfb60db0747d12cb41a79e7fb8f67c73de65b9f66760b0dab82599eeb2b160a"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jsec-0.3.0-linux-aarch64.tar.gz"
      sha256 "5379c329c8128f148db789228cfb0ede00eef54ce4e3d3fda3e3a21c0d2f9e1f"
    end
  end

  def install
    bin.install "jsec"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jsec --version")
  end
end
