# Generated by scripts/gen-formula.sh for v0.2.0 -- do not edit manually.
class Jtime < Formula
  desc "Timestamp converter helper tool (epoch, epoch-millis, ISO-8601)"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jtime-0.2.0-macos-x86_64.tar.gz"
      sha256 "1c3d8d56cac8b186044ca35825db4b95a69a3d7be84f4385a4e5cacb7eb9d5f8"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jtime-0.2.0-macos-aarch64.tar.gz"
      sha256 "4fe952b94ca38cd02cab800b16581bcc5e7139a356a42dfd0869f493081104bf"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jtime-0.2.0-linux-x86_64.tar.gz"
      sha256 "450fccfd078dd277d8b7a7ffffefea8bc79b8d3ec447604d54423e5f058b03e2"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/jtime-0.2.0-linux-aarch64.tar.gz"
      sha256 "edded60e24eb655d4acfa2465ee5128e9da99bfb6251749b066cf9156ebb9ae4"
    end
  end

  def install
    bin.install "jtime"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jtime --version")
  end
end
