# Generated by scripts/gen-formula.sh for v0.3.0 -- do not edit manually.
class Jtime < Formula
  desc "Timestamp converter helper tool (epoch, epoch-millis, ISO-8601)"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jtime-0.3.0-macos-x86_64.tar.gz"
      sha256 "aa87d02e01b442dc11f7a0087a3e800c241a9d673fb02e438ec4fb7fe96cd217"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jtime-0.3.0-macos-aarch64.tar.gz"
      sha256 "6a4625d3f62e1b69b862b606fa00f0ad049b8c247013760544064ba03a95708f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jtime-0.3.0-linux-x86_64.tar.gz"
      sha256 "4d89d351254049e75bda98876105784cc459a753e015c2bef095d4ed10f71c2c"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jtime-0.3.0-linux-aarch64.tar.gz"
      sha256 "067d16e9098bca65318dd899fa35ad737b3b502d599c0cfc0bd8196d003a2b54"
    end
  end

  def install
    bin.install "jtime"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jtime --version")
  end
end
