# Generated by scripts/gen-formula.sh for v0.3.0 -- do not edit manually.
class Juuid < Formula
  desc "UUID generator and parser helper tool (v4, v7)"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/juuid-0.3.0-macos-x86_64.tar.gz"
      sha256 "a92e644a2f04d42bca0a722007dbd7be8e97b1636e2f71a003843cf5c8b2d402"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/juuid-0.3.0-macos-aarch64.tar.gz"
      sha256 "7053148b582a5f292cd10b777148edd82f44a2b9c6ae85ba9a0d11a3561f02d8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/juuid-0.3.0-linux-x86_64.tar.gz"
      sha256 "4660c818670475374b129c59fbd4160416ccd02ddd533b439bc5129eeb068eeb"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/juuid-0.3.0-linux-aarch64.tar.gz"
      sha256 "d994ceb326e76cb9c59b8ce4b99e1de9b49010b070eee7c90ca3a9c62f9c3593"
    end
  end

  def install
    bin.install "juuid"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/juuid --version")
  end
end
