# Generated by scripts/gen-formula.sh for v0.2.0 -- do not edit manually.
class Juuid < Formula
  desc "UUID generator and parser helper tool (v4, v7)"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/juuid-0.2.0-macos-x86_64.tar.gz"
      sha256 "b4e0728503f234859c29e3a53cb902fca2bfbffbaf07777dd6e4a62694e77515"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/juuid-0.2.0-macos-aarch64.tar.gz"
      sha256 "3dd9937d4a40789f334f5494e4f343ceee6605e606130edb927e37db1a0f5ba5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/juuid-0.2.0-linux-x86_64.tar.gz"
      sha256 "f09ac193d87a6c5617c04f0ce85ce80e5b7923e27397adce0235f3ef16765fb3"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.2.0/juuid-0.2.0-linux-aarch64.tar.gz"
      sha256 "b576cc3a8905fb3535b6db6b3aa1217f2050c767896e9b2814576e76ecabb022"
    end
  end

  def install
    bin.install "juuid"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/juuid --version")
  end
end
