# Generated by scripts/gen-formula.sh for v0.3.0 -- do not edit manually.
class Jxpath < Formula
  desc "XML xpath helper tool (select, exists)"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jxpath-0.3.0-macos-x86_64.tar.gz"
      sha256 "480151d914943b7a15176209886b9c73fca671c735db0e569b6297f4b3784cc7"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jxpath-0.3.0-macos-aarch64.tar.gz"
      sha256 "5396f183997e06ab20a17d76ff258fe834e9fa38f5144c2fc5fb119011f806e5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jxpath-0.3.0-linux-x86_64.tar.gz"
      sha256 "38ed8b52de94b8b692278201cb2ecd7d18cf93faec3156fa0fae6cece4e4d6ff"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jxpath-0.3.0-linux-aarch64.tar.gz"
      sha256 "5b9ce0c4443bfb4ed10f7343c3a7e8d3e55e62e89bb198a56710513b39b91feb"
    end
  end

  def install
    bin.install "jxpath"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jxpath --version")
  end
end
