# Generated by scripts/gen-formula.sh for v0.3.0 -- do not edit manually.
class Jyaml < Formula
  desc "YAML helper tool (validate, tojson)"
  homepage "https://github.com/mhus/jknife"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jyaml-0.3.0-macos-x86_64.tar.gz"
      sha256 "1a24f8f53bac90ed5f3a724b1add7c119406f7e7fb1d19c75717b339b5ffdf14"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jyaml-0.3.0-macos-aarch64.tar.gz"
      sha256 "2398b44826307964b145bfc62a440a4d21d7a67103d198875ecbf5f161b05153"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jyaml-0.3.0-linux-x86_64.tar.gz"
      sha256 "b7a6f187342960e1d9c66b704aa6b38aa8e327e9eec7b5da4a4d63be050b4028"
    else
      url "https://github.com/mhus/jknife/releases/download/v0.3.0/jyaml-0.3.0-linux-aarch64.tar.gz"
      sha256 "9118d3de97fdbe22db39eadcff17a697811200b21f51006a498bd7382c6c6242"
    end
  end

  def install
    bin.install "jyaml"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jyaml --version")
  end
end
